# Generated by Django 4.2.3 on 2023-07-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_bookinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_death",
            field=models.DateField(auto_now=True, null=True, verbose_name="Died"),
        ),
        migrations.AlterUniqueTogether(
            name="author",
            unique_together={("first_name", "last_name")},
        ),
    ]
