# Generated by Django 4.2.3 on 2023-07-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("synopsis", models.TextField(max_length=500)),
                ("author", models.CharField(max_length=100)),
                ("available_copies", models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
